version: "3.9"
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes: ['./app:/app']

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ppls_champ

volumes:
  postgres_data: